# -*- coding: utf-8 -*-
"""proj103

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BK0suMubwx1KZKiqoSRmYWIHpggKPJZU
"""

from google.colab import files
data_to_load = files.upload()

import pandas as pd
import plotly.express as px

df = pd.read_csv("Copy+of+data+-+data.csv")

fig = px.scatter(df, x = "date", y = "cases", color = "country")
fig.show()